name: todo
description: TODO App.
version: 2.0.0+16
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  beamer: ^0.14.1
  bloc: ^7.2.0-dev.1
  dio: ^4.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.14.2
  get_it: ^7.2.0
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  shared_preferences: ^2.0.6

dev_dependencies:
  bloc_test: ^8.1.0
  build_runner: ^2.1.1
  flutter_gen_runner: ^3.1.1
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.1
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.4
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - config/ussd_codes.json
    - assets/images/

  fonts: 
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

flutter_icons:
  android: "launcher_icon"
  image_path: "logo.png"
  ios: true
  remove_alpha_ios: true
